# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 840)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(23)
        self.gridLayout_8.addWidget(self.tableWidget, 3, 1, 1, 1)
        self.Figure_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.Figure_tabWidget.setMinimumSize(QtCore.QSize(500, 500))
        self.Figure_tabWidget.setObjectName("Figure_tabWidget")
        self.LIV = QtWidgets.QWidget()
        self.LIV.setObjectName("LIV")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.LIV)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.MPLwidgetJV = QtWidgets.QWidget(self.LIV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MPLwidgetJV.sizePolicy().hasHeightForWidth())
        self.MPLwidgetJV.setSizePolicy(sizePolicy)
        self.MPLwidgetJV.setObjectName("MPLwidgetJV")
        self.gridLayout_MPLwidgetJV = QtWidgets.QGridLayout(self.MPLwidgetJV)
        self.gridLayout_MPLwidgetJV.setObjectName("gridLayout_MPLwidgetJV")
        self.gridLayout_9.addWidget(self.MPLwidgetJV, 0, 0, 1, 1)
        self.Figure_tabWidget.addTab(self.LIV, "")
        self.MPPT = QtWidgets.QWidget()
        self.MPPT.setObjectName("MPPT")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.MPPT)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.MPLwidgetMPPT = QtWidgets.QWidget(self.MPPT)
        self.MPLwidgetMPPT.setObjectName("MPLwidgetMPPT")
        self.gridLayout_MPLwidgetMPPT = QtWidgets.QGridLayout(self.MPLwidgetMPPT)
        self.gridLayout_MPLwidgetMPPT.setObjectName("gridLayout_MPLwidgetMPPT")
        self.gridLayout_10.addWidget(self.MPLwidgetMPPT, 0, 0, 1, 1)
        self.Figure_tabWidget.addTab(self.MPPT, "")
        self.DIV = QtWidgets.QWidget()
        self.DIV.setObjectName("DIV")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.DIV)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.MPLwidgetDIV = QtWidgets.QWidget(self.DIV)
        self.MPLwidgetDIV.setObjectName("MPLwidgetDIV")
        self.gridLayout_MPLwidgetDIV = QtWidgets.QGridLayout(self.MPLwidgetDIV)
        self.gridLayout_MPLwidgetDIV.setObjectName("gridLayout_MPLwidgetDIV")
        self.gridLayout_12.addWidget(self.MPLwidgetDIV, 0, 0, 1, 1)
        self.Figure_tabWidget.addTab(self.DIV, "")
        self.gridLayout_8.addWidget(self.Figure_tabWidget, 0, 1, 3, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(600, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(650, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_CheckIntensity = QtWidgets.QGroupBox(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_CheckIntensity.setPalette(palette)
        self.groupBox_CheckIntensity.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_CheckIntensity.setAutoFillBackground(True)
        self.groupBox_CheckIntensity.setFlat(False)
        self.groupBox_CheckIntensity.setCheckable(False)
        self.groupBox_CheckIntensity.setObjectName("groupBox_CheckIntensity")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_CheckIntensity)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_CheckIntensity)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 2)
        self.doubleSpinBox_DiodeNominalCurrent = QtWidgets.QDoubleSpinBox(self.groupBox_CheckIntensity)
        self.doubleSpinBox_DiodeNominalCurrent.setDecimals(6)
        self.doubleSpinBox_DiodeNominalCurrent.setMaximum(1000.0)
        self.doubleSpinBox_DiodeNominalCurrent.setObjectName("doubleSpinBox_DiodeNominalCurrent")
        self.gridLayout_2.addWidget(self.doubleSpinBox_DiodeNominalCurrent, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_CheckIntensity)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.doubleSpinBox_MeasuredDiodeCurrent = QtWidgets.QDoubleSpinBox(self.groupBox_CheckIntensity)
        self.doubleSpinBox_MeasuredDiodeCurrent.setReadOnly(True)
        self.doubleSpinBox_MeasuredDiodeCurrent.setDecimals(6)
        self.doubleSpinBox_MeasuredDiodeCurrent.setMaximum(1000.0)
        self.doubleSpinBox_MeasuredDiodeCurrent.setObjectName("doubleSpinBox_MeasuredDiodeCurrent")
        self.gridLayout_2.addWidget(self.doubleSpinBox_MeasuredDiodeCurrent, 1, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox_CheckIntensity)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.doubleSpinBox_NumbSun = QtWidgets.QDoubleSpinBox(self.groupBox_CheckIntensity)
        self.doubleSpinBox_NumbSun.setEnabled(True)
        self.doubleSpinBox_NumbSun.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_NumbSun.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.doubleSpinBox_NumbSun.setReadOnly(True)
        self.doubleSpinBox_NumbSun.setDecimals(3)
        self.doubleSpinBox_NumbSun.setObjectName("doubleSpinBox_NumbSun")
        self.gridLayout_2.addWidget(self.doubleSpinBox_NumbSun, 2, 1, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.groupBox_CheckIntensity)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.doubleSpinBox_Temperature = QtWidgets.QDoubleSpinBox(self.groupBox_CheckIntensity)
        self.doubleSpinBox_Temperature.setDecimals(1)
        self.doubleSpinBox_Temperature.setProperty("value", 25.0)
        self.doubleSpinBox_Temperature.setObjectName("doubleSpinBox_Temperature")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Temperature, 3, 1, 1, 2)
        self.pushButton_MeasureIntensityDiode = QtWidgets.QPushButton(self.groupBox_CheckIntensity)
        self.pushButton_MeasureIntensityDiode.setObjectName("pushButton_MeasureIntensityDiode")
        self.gridLayout_2.addWidget(self.pushButton_MeasureIntensityDiode, 4, 0, 1, 1)
        self.radioButton_Assume1sun = QtWidgets.QRadioButton(self.groupBox_CheckIntensity)
        self.radioButton_Assume1sun.setObjectName("radioButton_Assume1sun")
        self.gridLayout_2.addWidget(self.radioButton_Assume1sun, 4, 1, 1, 2)
        self.gridLayout_7.addWidget(self.groupBox_CheckIntensity, 2, 0, 1, 2)
        self.groupBox_JVsweepParam = QtWidgets.QGroupBox(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_JVsweepParam.setPalette(palette)
        self.groupBox_JVsweepParam.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_JVsweepParam.setAutoFillBackground(True)
        self.groupBox_JVsweepParam.setFlat(False)
        self.groupBox_JVsweepParam.setCheckable(False)
        self.groupBox_JVsweepParam.setObjectName("groupBox_JVsweepParam")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_JVsweepParam)
        self.gridLayout.setObjectName("gridLayout")
        self.label_15 = QtWidgets.QLabel(self.groupBox_JVsweepParam)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 0, 1, 1)
        self.doubleSpinBox_JVminvoltage = QtWidgets.QDoubleSpinBox(self.groupBox_JVsweepParam)
        self.doubleSpinBox_JVminvoltage.setDecimals(1)
        self.doubleSpinBox_JVminvoltage.setMinimum(-10000.0)
        self.doubleSpinBox_JVminvoltage.setMaximum(10000.0)
        self.doubleSpinBox_JVminvoltage.setProperty("value", -200.0)
        self.doubleSpinBox_JVminvoltage.setObjectName("doubleSpinBox_JVminvoltage")
        self.gridLayout.addWidget(self.doubleSpinBox_JVminvoltage, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_JVsweepParam)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_JVsweepParam)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_JVsweepParam)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 6, 0, 1, 1)
        self.doubleSpinBox_JVdelaypoints = QtWidgets.QDoubleSpinBox(self.groupBox_JVsweepParam)
        self.doubleSpinBox_JVdelaypoints.setDecimals(0)
        self.doubleSpinBox_JVdelaypoints.setMaximum(10000.0)
        self.doubleSpinBox_JVdelaypoints.setProperty("value", 50.0)
        self.doubleSpinBox_JVdelaypoints.setObjectName("doubleSpinBox_JVdelaypoints")
        self.gridLayout.addWidget(self.doubleSpinBox_JVdelaypoints, 5, 1, 1, 1)
        self.comboBox_JVscandirection = QtWidgets.QComboBox(self.groupBox_JVsweepParam)
        self.comboBox_JVscandirection.setObjectName("comboBox_JVscandirection")
        self.comboBox_JVscandirection.addItem("")
        self.comboBox_JVscandirection.addItem("")
        self.comboBox_JVscandirection.addItem("")
        self.comboBox_JVscandirection.addItem("")
        self.gridLayout.addWidget(self.comboBox_JVscandirection, 7, 1, 1, 1)
        self.doubleSpinBox_JVstepsize = QtWidgets.QDoubleSpinBox(self.groupBox_JVsweepParam)
        self.doubleSpinBox_JVstepsize.setDecimals(1)
        self.doubleSpinBox_JVstepsize.setMaximum(1000.0)
        self.doubleSpinBox_JVstepsize.setProperty("value", 20.0)
        self.doubleSpinBox_JVstepsize.setObjectName("doubleSpinBox_JVstepsize")
        self.gridLayout.addWidget(self.doubleSpinBox_JVstepsize, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_JVsweepParam)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_JVsweepParam)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 5, 0, 1, 1)
        self.doubleSpinBox_JVdelayshutter = QtWidgets.QDoubleSpinBox(self.groupBox_JVsweepParam)
        self.doubleSpinBox_JVdelayshutter.setDecimals(0)
        self.doubleSpinBox_JVdelayshutter.setMaximum(10000.0)
        self.doubleSpinBox_JVdelayshutter.setProperty("value", 100.0)
        self.doubleSpinBox_JVdelayshutter.setObjectName("doubleSpinBox_JVdelayshutter")
        self.gridLayout.addWidget(self.doubleSpinBox_JVdelayshutter, 6, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_JVsweepParam)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.doubleSpinBox_JVmaxvoltage = QtWidgets.QDoubleSpinBox(self.groupBox_JVsweepParam)
        self.doubleSpinBox_JVmaxvoltage.setDecimals(1)
        self.doubleSpinBox_JVmaxvoltage.setMinimum(-10000.0)
        self.doubleSpinBox_JVmaxvoltage.setMaximum(10000.0)
        self.doubleSpinBox_JVmaxvoltage.setProperty("value", 1200.0)
        self.doubleSpinBox_JVmaxvoltage.setObjectName("doubleSpinBox_JVmaxvoltage")
        self.gridLayout.addWidget(self.doubleSpinBox_JVmaxvoltage, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_JVsweepParam)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 7, 0, 1, 1)
        self.doubleSpinBox_JVcurrentlimit = QtWidgets.QDoubleSpinBox(self.groupBox_JVsweepParam)
        self.doubleSpinBox_JVcurrentlimit.setMaximum(100000.0)
        self.doubleSpinBox_JVcurrentlimit.setProperty("value", 100.0)
        self.doubleSpinBox_JVcurrentlimit.setObjectName("doubleSpinBox_JVcurrentlimit")
        self.gridLayout.addWidget(self.doubleSpinBox_JVcurrentlimit, 3, 1, 1, 1)
        self.doubleSpinBox_JVintegrationtime = QtWidgets.QDoubleSpinBox(self.groupBox_JVsweepParam)
        self.doubleSpinBox_JVintegrationtime.setDecimals(0)
        self.doubleSpinBox_JVintegrationtime.setMaximum(100000.0)
        self.doubleSpinBox_JVintegrationtime.setProperty("value", 50.0)
        self.doubleSpinBox_JVintegrationtime.setObjectName("doubleSpinBox_JVintegrationtime")
        self.gridLayout.addWidget(self.doubleSpinBox_JVintegrationtime, 4, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_JVsweepParam, 2, 2, 1, 1)
        self.groupBox_MPPTParam = QtWidgets.QGroupBox(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_MPPTParam.setPalette(palette)
        self.groupBox_MPPTParam.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_MPPTParam.setAutoFillBackground(True)
        self.groupBox_MPPTParam.setFlat(False)
        self.groupBox_MPPTParam.setCheckable(False)
        self.groupBox_MPPTParam.setObjectName("groupBox_MPPTParam")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_MPPTParam)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_20 = QtWidgets.QLabel(self.groupBox_MPPTParam)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 0, 0, 1, 2)
        self.doubleSpinBox_MPPTstartvoltage = QtWidgets.QDoubleSpinBox(self.groupBox_MPPTParam)
        self.doubleSpinBox_MPPTstartvoltage.setDecimals(1)
        self.doubleSpinBox_MPPTstartvoltage.setMinimum(-10000.0)
        self.doubleSpinBox_MPPTstartvoltage.setMaximum(10000.0)
        self.doubleSpinBox_MPPTstartvoltage.setProperty("value", 500.0)
        self.doubleSpinBox_MPPTstartvoltage.setObjectName("doubleSpinBox_MPPTstartvoltage")
        self.gridLayout_5.addWidget(self.doubleSpinBox_MPPTstartvoltage, 0, 2, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.groupBox_MPPTParam)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 1, 0, 1, 1)
        self.spinBox_MPPTstepsize = QtWidgets.QSpinBox(self.groupBox_MPPTParam)
        self.spinBox_MPPTstepsize.setMaximum(100)
        self.spinBox_MPPTstepsize.setProperty("value", 5)
        self.spinBox_MPPTstepsize.setObjectName("spinBox_MPPTstepsize")
        self.gridLayout_5.addWidget(self.spinBox_MPPTstepsize, 1, 2, 1, 2)
        self.horizontalSlider_MPPTstepsize = QtWidgets.QSlider(self.groupBox_MPPTParam)
        self.horizontalSlider_MPPTstepsize.setMaximum(100)
        self.horizontalSlider_MPPTstepsize.setProperty("value", 5)
        self.horizontalSlider_MPPTstepsize.setTracking(True)
        self.horizontalSlider_MPPTstepsize.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_MPPTstepsize.setObjectName("horizontalSlider_MPPTstepsize")
        self.gridLayout_5.addWidget(self.horizontalSlider_MPPTstepsize, 2, 0, 1, 4)
        self.label_22 = QtWidgets.QLabel(self.groupBox_MPPTParam)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 3, 0, 1, 2)
        self.doubleSpinBox_MPPTvoltagelimit = QtWidgets.QDoubleSpinBox(self.groupBox_MPPTParam)
        self.doubleSpinBox_MPPTvoltagelimit.setDecimals(1)
        self.doubleSpinBox_MPPTvoltagelimit.setMaximum(100000.0)
        self.doubleSpinBox_MPPTvoltagelimit.setProperty("value", 2000.0)
        self.doubleSpinBox_MPPTvoltagelimit.setObjectName("doubleSpinBox_MPPTvoltagelimit")
        self.gridLayout_5.addWidget(self.doubleSpinBox_MPPTvoltagelimit, 3, 2, 1, 2)
        self.label_23 = QtWidgets.QLabel(self.groupBox_MPPTParam)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 4, 0, 1, 3)
        self.doubleSpinBox_MPPTdelaypoints = QtWidgets.QDoubleSpinBox(self.groupBox_MPPTParam)
        self.doubleSpinBox_MPPTdelaypoints.setDecimals(0)
        self.doubleSpinBox_MPPTdelaypoints.setMaximum(9999999.0)
        self.doubleSpinBox_MPPTdelaypoints.setProperty("value", 50.0)
        self.doubleSpinBox_MPPTdelaypoints.setObjectName("doubleSpinBox_MPPTdelaypoints")
        self.gridLayout_5.addWidget(self.doubleSpinBox_MPPTdelaypoints, 4, 3, 1, 1)
        self.checkBox_MPPTlighton = QtWidgets.QCheckBox(self.groupBox_MPPTParam)
        self.checkBox_MPPTlighton.setObjectName("checkBox_MPPTlighton")
        self.gridLayout_5.addWidget(self.checkBox_MPPTlighton, 5, 0, 1, 1)
        self.checkBox_MPPTlightonafter = QtWidgets.QCheckBox(self.groupBox_MPPTParam)
        self.checkBox_MPPTlightonafter.setObjectName("checkBox_MPPTlightonafter")
        self.gridLayout_5.addWidget(self.checkBox_MPPTlightonafter, 5, 1, 1, 3)
        self.gridLayout_7.addWidget(self.groupBox_MPPTParam, 3, 0, 1, 2)
        self.groupBox_SavingConfig = QtWidgets.QGroupBox(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_SavingConfig.setPalette(palette)
        self.groupBox_SavingConfig.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_SavingConfig.setAutoFillBackground(True)
        self.groupBox_SavingConfig.setFlat(False)
        self.groupBox_SavingConfig.setCheckable(False)
        self.groupBox_SavingConfig.setObjectName("groupBox_SavingConfig")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_SavingConfig)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_UserName = QtWidgets.QLineEdit(self.groupBox_SavingConfig)
        self.lineEdit_UserName.setObjectName("lineEdit_UserName")
        self.gridLayout_3.addWidget(self.lineEdit_UserName, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_SavingConfig)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_SampleName = QtWidgets.QLineEdit(self.groupBox_SavingConfig)
        self.lineEdit_SampleName.setObjectName("lineEdit_SampleName")
        self.gridLayout_3.addWidget(self.lineEdit_SampleName, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_SavingConfig)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_SavingConfig)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_Comment = QtWidgets.QLineEdit(self.groupBox_SavingConfig)
        self.lineEdit_Comment.setObjectName("lineEdit_Comment")
        self.gridLayout_3.addWidget(self.lineEdit_Comment, 1, 1, 1, 3)
        self.gridLayout_7.addWidget(self.groupBox_SavingConfig, 0, 0, 1, 3)
        self.groupBox_SubstrateConfig = QtWidgets.QGroupBox(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_SubstrateConfig.setPalette(palette)
        self.groupBox_SubstrateConfig.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_SubstrateConfig.setAutoFillBackground(True)
        self.groupBox_SubstrateConfig.setFlat(False)
        self.groupBox_SubstrateConfig.setCheckable(False)
        self.groupBox_SubstrateConfig.setObjectName("groupBox_SubstrateConfig")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_SubstrateConfig)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_pixA = QtWidgets.QCheckBox(self.groupBox_SubstrateConfig)
        self.checkBox_pixA.setObjectName("checkBox_pixA")
        self.gridLayout_6.addWidget(self.checkBox_pixA, 0, 0, 1, 1)
        self.doubleSpinBox_pixAarea = QtWidgets.QDoubleSpinBox(self.groupBox_SubstrateConfig)
        self.doubleSpinBox_pixAarea.setMaximum(1000.0)
        self.doubleSpinBox_pixAarea.setProperty("value", 0.06)
        self.doubleSpinBox_pixAarea.setObjectName("doubleSpinBox_pixAarea")
        self.gridLayout_6.addWidget(self.doubleSpinBox_pixAarea, 0, 1, 1, 1)
        self.checkBox_pixB = QtWidgets.QCheckBox(self.groupBox_SubstrateConfig)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkBox_pixB.setPalette(palette)
        self.checkBox_pixB.setObjectName("checkBox_pixB")
        self.gridLayout_6.addWidget(self.checkBox_pixB, 0, 2, 1, 1)
        self.doubleSpinBox_pixBarea = QtWidgets.QDoubleSpinBox(self.groupBox_SubstrateConfig)
        self.doubleSpinBox_pixBarea.setMaximum(1000.0)
        self.doubleSpinBox_pixBarea.setProperty("value", 0.06)
        self.doubleSpinBox_pixBarea.setObjectName("doubleSpinBox_pixBarea")
        self.gridLayout_6.addWidget(self.doubleSpinBox_pixBarea, 0, 3, 1, 1)
        self.checkBox_pixC = QtWidgets.QCheckBox(self.groupBox_SubstrateConfig)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(88, 88, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkBox_pixC.setPalette(palette)
        self.checkBox_pixC.setObjectName("checkBox_pixC")
        self.gridLayout_6.addWidget(self.checkBox_pixC, 1, 0, 1, 1)
        self.doubleSpinBox_pixCarea = QtWidgets.QDoubleSpinBox(self.groupBox_SubstrateConfig)
        self.doubleSpinBox_pixCarea.setMaximum(1000.0)
        self.doubleSpinBox_pixCarea.setProperty("value", 0.06)
        self.doubleSpinBox_pixCarea.setObjectName("doubleSpinBox_pixCarea")
        self.gridLayout_6.addWidget(self.doubleSpinBox_pixCarea, 1, 1, 1, 1)
        self.checkBox_pixD = QtWidgets.QCheckBox(self.groupBox_SubstrateConfig)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(88, 88, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkBox_pixD.setPalette(palette)
        self.checkBox_pixD.setObjectName("checkBox_pixD")
        self.gridLayout_6.addWidget(self.checkBox_pixD, 1, 2, 1, 1)
        self.doubleSpinBox_pixDarea = QtWidgets.QDoubleSpinBox(self.groupBox_SubstrateConfig)
        self.doubleSpinBox_pixDarea.setMaximum(1000.0)
        self.doubleSpinBox_pixDarea.setProperty("value", 0.06)
        self.doubleSpinBox_pixDarea.setObjectName("doubleSpinBox_pixDarea")
        self.gridLayout_6.addWidget(self.doubleSpinBox_pixDarea, 1, 3, 1, 1)
        self.checkBox_pixE = QtWidgets.QCheckBox(self.groupBox_SubstrateConfig)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(88, 88, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkBox_pixE.setPalette(palette)
        self.checkBox_pixE.setObjectName("checkBox_pixE")
        self.gridLayout_6.addWidget(self.checkBox_pixE, 2, 0, 1, 1)
        self.doubleSpinBox_pixEarea = QtWidgets.QDoubleSpinBox(self.groupBox_SubstrateConfig)
        self.doubleSpinBox_pixEarea.setMaximum(1000.0)
        self.doubleSpinBox_pixEarea.setProperty("value", 0.06)
        self.doubleSpinBox_pixEarea.setObjectName("doubleSpinBox_pixEarea")
        self.gridLayout_6.addWidget(self.doubleSpinBox_pixEarea, 2, 1, 1, 1)
        self.checkBox_pixF = QtWidgets.QCheckBox(self.groupBox_SubstrateConfig)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(88, 88, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.checkBox_pixF.setPalette(palette)
        self.checkBox_pixF.setObjectName("checkBox_pixF")
        self.gridLayout_6.addWidget(self.checkBox_pixF, 2, 2, 1, 1)
        self.doubleSpinBox_pixFarea = QtWidgets.QDoubleSpinBox(self.groupBox_SubstrateConfig)
        self.doubleSpinBox_pixFarea.setMaximum(1000.0)
        self.doubleSpinBox_pixFarea.setProperty("value", 0.06)
        self.doubleSpinBox_pixFarea.setObjectName("doubleSpinBox_pixFarea")
        self.gridLayout_6.addWidget(self.doubleSpinBox_pixFarea, 2, 3, 1, 1)
        self.radioButton_pixAll = QtWidgets.QRadioButton(self.groupBox_SubstrateConfig)
        self.radioButton_pixAll.setObjectName("radioButton_pixAll")
        self.gridLayout_6.addWidget(self.radioButton_pixAll, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_SubstrateConfig)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 3, 1, 1, 3)
        self.gridLayout_7.addWidget(self.groupBox_SubstrateConfig, 3, 2, 1, 1)
        self.groupBox_Measurement = QtWidgets.QGroupBox(self.frame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(177, 177, 177))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_Measurement.setPalette(palette)
        self.groupBox_Measurement.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.groupBox_Measurement.setAutoFillBackground(True)
        self.groupBox_Measurement.setFlat(False)
        self.groupBox_Measurement.setCheckable(False)
        self.groupBox_Measurement.setObjectName("groupBox_Measurement")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_Measurement)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_4 = QtWidgets.QLabel(self.groupBox_Measurement)
        self.label_4.setObjectName("label_4")
        self.gridLayout_18.addWidget(self.label_4, 0, 1, 1, 1)
        self.comboBox_MeasType = QtWidgets.QComboBox(self.groupBox_Measurement)
        self.comboBox_MeasType.setObjectName("comboBox_MeasType")
        self.comboBox_MeasType.addItem("")
        self.comboBox_MeasType.addItem("")
        self.comboBox_MeasType.addItem("")
        self.comboBox_MeasType.addItem("")
        self.comboBox_MeasType.addItem("")
        self.comboBox_MeasType.addItem("")
        self.comboBox_MeasType.addItem("")
        self.comboBox_MeasType.addItem("")
        self.comboBox_MeasType.addItem("")
        self.comboBox_MeasType.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_MeasType, 0, 2, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox_Measurement)
        self.label_6.setObjectName("label_6")
        self.gridLayout_18.addWidget(self.label_6, 1, 1, 1, 2)
        self.spinBox_RepNumb = QtWidgets.QSpinBox(self.groupBox_Measurement)
        self.spinBox_RepNumb.setMinimum(0)
        self.spinBox_RepNumb.setProperty("value", 1)
        self.spinBox_RepNumb.setObjectName("spinBox_RepNumb")
        self.gridLayout_18.addWidget(self.spinBox_RepNumb, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_Measurement)
        self.label_7.setObjectName("label_7")
        self.gridLayout_18.addWidget(self.label_7, 2, 1, 1, 2)
        self.spinBox_RepDelay = QtWidgets.QSpinBox(self.groupBox_Measurement)
        self.spinBox_RepDelay.setMaximum(10000)
        self.spinBox_RepDelay.setProperty("value", 10)
        self.spinBox_RepDelay.setObjectName("spinBox_RepDelay")
        self.gridLayout_18.addWidget(self.spinBox_RepDelay, 2, 3, 1, 1)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.groupBox_Measurement)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_StartMeas = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_StartMeas.setObjectName("pushButton_StartMeas")
        self.gridLayout_4.addWidget(self.pushButton_StartMeas, 0, 0, 1, 1)
        self.pushButton_StopMeas = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_StopMeas.setObjectName("pushButton_StopMeas")
        self.gridLayout_4.addWidget(self.pushButton_StopMeas, 0, 1, 1, 1)
        self.pushButton_OpenCloseShutter = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_OpenCloseShutter.setObjectName("pushButton_OpenCloseShutter")
        self.gridLayout_4.addWidget(self.pushButton_OpenCloseShutter, 1, 0, 1, 1)
        self.pushButton_StopMppt = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_StopMppt.setObjectName("pushButton_StopMppt")
        self.gridLayout_4.addWidget(self.pushButton_StopMppt, 1, 1, 1, 1)
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.pushButton_PlotfromTable = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_PlotfromTable.setObjectName("pushButton_PlotfromTable")
        self.gridLayout_17.addWidget(self.pushButton_PlotfromTable, 0, 0, 1, 1)
        self.pushButton_cleargraph = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_cleargraph.setObjectName("pushButton_cleargraph")
        self.gridLayout_17.addWidget(self.pushButton_cleargraph, 0, 1, 1, 1)
        self.pushButton_LoadAllDATAinTable = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_LoadAllDATAinTable.setObjectName("pushButton_LoadAllDATAinTable")
        self.gridLayout_17.addWidget(self.pushButton_LoadAllDATAinTable, 1, 0, 1, 1)
        self.comboBox_cleargraph = QtWidgets.QComboBox(self.tab_7)
        self.comboBox_cleargraph.setObjectName("comboBox_cleargraph")
        self.comboBox_cleargraph.addItem("")
        self.comboBox_cleargraph.addItem("")
        self.comboBox_cleargraph.addItem("")
        self.gridLayout_17.addWidget(self.comboBox_cleargraph, 1, 1, 1, 1)
        self.pushButton_exportgraphandfile = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_exportgraphandfile.setObjectName("pushButton_exportgraphandfile")
        self.gridLayout_17.addWidget(self.pushButton_exportgraphandfile, 2, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_7, "")
        self.gridLayout_18.addWidget(self.tabWidget_3, 0, 0, 3, 1)
        self.gridLayout_7.addWidget(self.groupBox_Measurement, 1, 0, 1, 3)
        self.gridLayout_11.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_15.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_15.addWidget(self.label_25, 0, 1, 1, 1)
        self.comboBox_DBTime = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_DBTime.setObjectName("comboBox_DBTime")
        self.gridLayout_15.addWidget(self.comboBox_DBTime, 1, 0, 1, 1)
        self.comboBox_DBTimeYaxis = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_DBTimeYaxis.setObjectName("comboBox_DBTimeYaxis")
        self.gridLayout_15.addWidget(self.comboBox_DBTimeYaxis, 1, 1, 1, 1)
        self.pushButton_DBTime_remove = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_DBTime_remove.setObjectName("pushButton_DBTime_remove")
        self.gridLayout_15.addWidget(self.pushButton_DBTime_remove, 1, 4, 1, 1)
        self.listWidget_DBTime_Restrictions = QtWidgets.QListWidget(self.tab_4)
        self.listWidget_DBTime_Restrictions.setObjectName("listWidget_DBTime_Restrictions")
        self.gridLayout_15.addWidget(self.listWidget_DBTime_Restrictions, 2, 0, 6, 2)
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout_15.addWidget(self.label_26, 2, 2, 1, 1)
        self.pushButton_DBTime_Add = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_DBTime_Add.setObjectName("pushButton_DBTime_Add")
        self.gridLayout_15.addWidget(self.pushButton_DBTime_Add, 2, 3, 1, 1)
        self.listWidget_DBTime_chosenRestrictions = QtWidgets.QListWidget(self.tab_4)
        self.listWidget_DBTime_chosenRestrictions.setObjectName("listWidget_DBTime_chosenRestrictions")
        self.gridLayout_15.addWidget(self.listWidget_DBTime_chosenRestrictions, 2, 4, 6, 1)
        self.comboBox_DBTime_restrictions = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_DBTime_restrictions.setObjectName("comboBox_DBTime_restrictions")
        self.gridLayout_15.addWidget(self.comboBox_DBTime_restrictions, 3, 2, 1, 2)
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setObjectName("label_27")
        self.gridLayout_15.addWidget(self.label_27, 4, 2, 1, 1)
        self.lineEdit_DBTime_From = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_DBTime_From.setObjectName("lineEdit_DBTime_From")
        self.gridLayout_15.addWidget(self.lineEdit_DBTime_From, 5, 2, 1, 2)
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setObjectName("label_28")
        self.gridLayout_15.addWidget(self.label_28, 6, 2, 1, 1)
        self.lineEdit_DBTime_To = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_DBTime_To.setObjectName("lineEdit_DBTime_To")
        self.gridLayout_15.addWidget(self.lineEdit_DBTime_To, 7, 2, 1, 2)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.gridLayout_16.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.widget_DB = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_DB.sizePolicy().hasHeightForWidth())
        self.widget_DB.setSizePolicy(sizePolicy)
        self.widget_DB.setObjectName("widget_DB")
        self.gridLayout_mplDB = QtWidgets.QGridLayout(self.widget_DB)
        self.gridLayout_mplDB.setObjectName("gridLayout_mplDB")
        self.gridLayout_16.addWidget(self.widget_DB, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_settings = QtWidgets.QAction(MainWindow)
        self.actionLoad_settings.setObjectName("actionLoad_settings")
        self.actionSave_settings = QtWidgets.QAction(MainWindow)
        self.actionSave_settings.setObjectName("actionSave_settings")
        self.menuFile.addAction(self.actionLoad_settings)
        self.menuFile.addAction(self.actionSave_settings)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.Figure_tabWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.radioButton_pixAll.clicked['bool'].connect(self.checkBox_pixC.setChecked)
        self.radioButton_pixAll.clicked['bool'].connect(self.checkBox_pixD.setChecked)
        self.horizontalSlider_MPPTstepsize.valueChanged['int'].connect(self.spinBox_MPPTstepsize.setValue)
        self.radioButton_pixAll.clicked['bool'].connect(self.checkBox_pixA.setChecked)
        self.radioButton_pixAll.clicked['bool'].connect(self.checkBox_pixB.setChecked)
        self.radioButton_pixAll.clicked['bool'].connect(self.checkBox_pixE.setChecked)
        self.spinBox_MPPTstepsize.valueChanged['int'].connect(self.horizontalSlider_MPPTstepsize.setValue)
        self.radioButton_pixAll.clicked['bool'].connect(self.checkBox_pixF.setChecked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Eff. (%)"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "FF (%)"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Voc (mV)"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Jsc (mA/cm2)"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Isc raw (A)"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Roc (ohm/cm2)"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Rsc (ohm/cm2)"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Pmpp (W/m2)"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Vmpp (mV)"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Jmpp (mA/cm2)"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "DateTime"))
        self.Figure_tabWidget.setTabText(self.Figure_tabWidget.indexOf(self.LIV), _translate("MainWindow", "LIV"))
        self.Figure_tabWidget.setTabText(self.Figure_tabWidget.indexOf(self.MPPT), _translate("MainWindow", "MPPT"))
        self.Figure_tabWidget.setTabText(self.Figure_tabWidget.indexOf(self.DIV), _translate("MainWindow", "DIV"))
        self.groupBox_CheckIntensity.setTitle(_translate("MainWindow", "Check Intensity"))
        self.label_8.setText(_translate("MainWindow", "Diode 1sun nominal current (A):"))
        self.label_10.setText(_translate("MainWindow", "Measured current (A):"))
        self.label_11.setText(_translate("MainWindow", "Actual intensity (#sun):"))
        self.label_12.setText(_translate("MainWindow", "Temperature (C):"))
        self.pushButton_MeasureIntensityDiode.setText(_translate("MainWindow", "Measure Intensity"))
        self.radioButton_Assume1sun.setText(_translate("MainWindow", "Assume 1sun"))
        self.groupBox_JVsweepParam.setTitle(_translate("MainWindow", "JV sweep parameters"))
        self.label_15.setText(_translate("MainWindow", "Step size (mV):"))
        self.label_24.setText(_translate("MainWindow", "Integration time (ms):"))
        self.label_13.setText(_translate("MainWindow", "Min. voltage (mV):"))
        self.label_18.setText(_translate("MainWindow", "Delay after shutter move:"))
        self.comboBox_JVscandirection.setItemText(0, _translate("MainWindow", "Reverse + Forward"))
        self.comboBox_JVscandirection.setItemText(1, _translate("MainWindow", "Forward + Reverse"))
        self.comboBox_JVscandirection.setItemText(2, _translate("MainWindow", "Reverse"))
        self.comboBox_JVscandirection.setItemText(3, _translate("MainWindow", "Forward"))
        self.label_16.setText(_translate("MainWindow", "Current limit (A):"))
        self.label_17.setText(_translate("MainWindow", "Delay between steps (ms):"))
        self.label_14.setText(_translate("MainWindow", "Max. voltage (mV):"))
        self.label_19.setText(_translate("MainWindow", "Scan direction:"))
        self.groupBox_MPPTParam.setTitle(_translate("MainWindow", "MPPT parameters"))
        self.label_20.setText(_translate("MainWindow", "Start voltage (mV):"))
        self.label_21.setText(_translate("MainWindow", "Step size (mV):"))
        self.label_22.setText(_translate("MainWindow", "Voltage limit (mV):"))
        self.label_23.setText(_translate("MainWindow", "Delay between points (ms):"))
        self.checkBox_MPPTlighton.setText(_translate("MainWindow", "Light on?"))
        self.checkBox_MPPTlightonafter.setText(_translate("MainWindow", "keep light on after?"))
        self.groupBox_SavingConfig.setTitle(_translate("MainWindow", "Saving config."))
        self.label_3.setText(_translate("MainWindow", "Comment"))
        self.label_2.setText(_translate("MainWindow", "Sample Name"))
        self.label.setText(_translate("MainWindow", "UserName"))
        self.groupBox_SubstrateConfig.setTitle(_translate("MainWindow", "Substrate config."))
        self.checkBox_pixA.setText(_translate("MainWindow", "Pixel A"))
        self.checkBox_pixB.setText(_translate("MainWindow", "Pixel B"))
        self.checkBox_pixC.setText(_translate("MainWindow", "Pixel C"))
        self.checkBox_pixD.setText(_translate("MainWindow", "Pixel D"))
        self.checkBox_pixE.setText(_translate("MainWindow", "Pixel E"))
        self.checkBox_pixF.setText(_translate("MainWindow", "Pixel F"))
        self.radioButton_pixAll.setText(_translate("MainWindow", "All"))
        self.label_5.setText(_translate("MainWindow", "solid line = Reverse, dashed = forward"))
        self.groupBox_Measurement.setTitle(_translate("MainWindow", "Measurement"))
        self.label_4.setText(_translate("MainWindow", "Meas. type"))
        self.comboBox_MeasType.setItemText(0, _translate("MainWindow", "LIV"))
        self.comboBox_MeasType.setItemText(1, _translate("MainWindow", "DIV"))
        self.comboBox_MeasType.setItemText(2, _translate("MainWindow", "DIV-LIV"))
        self.comboBox_MeasType.setItemText(3, _translate("MainWindow", "MPPT"))
        self.comboBox_MeasType.setItemText(4, _translate("MainWindow", "LIV-MPPT-LIV"))
        self.comboBox_MeasType.setItemText(5, _translate("MainWindow", "LIV-bestpixMPPT-LIV"))
        self.comboBox_MeasType.setItemText(6, _translate("MainWindow", "DIV-LIV-MPPT-LIV"))
        self.comboBox_MeasType.setItemText(7, _translate("MainWindow", "DIV-LIV-bestpixMPPT-LIV"))
        self.comboBox_MeasType.setItemText(8, _translate("MainWindow", "FixedVoltage"))
        self.comboBox_MeasType.setItemText(9, _translate("MainWindow", "FixedCurrent"))
        self.label_6.setText(_translate("MainWindow", "# of repetitions of sequence"))
        self.label_7.setText(_translate("MainWindow", "Delay between rep. (ms)"))
        self.pushButton_StartMeas.setText(_translate("MainWindow", "Start Measurement"))
        self.pushButton_StopMeas.setText(_translate("MainWindow", "Stop Meas. Sequence"))
        self.pushButton_OpenCloseShutter.setText(_translate("MainWindow", "Open/Close shutter"))
        self.pushButton_StopMppt.setText(_translate("MainWindow", "Stop only MPPT"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Meas."))
        self.pushButton_PlotfromTable.setText(_translate("MainWindow", "Plot only selected data from Table"))
        self.pushButton_cleargraph.setText(_translate("MainWindow", "Clear graph"))
        self.pushButton_LoadAllDATAinTable.setText(_translate("MainWindow", "Load all data of the session in Table"))
        self.comboBox_cleargraph.setItemText(0, _translate("MainWindow", "LIV"))
        self.comboBox_cleargraph.setItemText(1, _translate("MainWindow", "MPPT"))
        self.comboBox_cleargraph.setItemText(2, _translate("MainWindow", "DIV"))
        self.pushButton_exportgraphandfile.setText(_translate("MainWindow", "Export graph with txt rawdata files"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "Clear/Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Measurements"))
        self.label_9.setText(_translate("MainWindow", "Time"))
        self.label_25.setText(_translate("MainWindow", "y-axis"))
        self.pushButton_DBTime_remove.setText(_translate("MainWindow", "Remove restriction"))
        self.label_26.setText(_translate("MainWindow", "Restriction"))
        self.pushButton_DBTime_Add.setText(_translate("MainWindow", "Add"))
        self.label_27.setText(_translate("MainWindow", "From"))
        self.label_28.setText(_translate("MainWindow", "To"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Time Evol"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "BoxPlots"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Database Reading"))
        self.menuFile.setTitle(_translate("MainWindow", "Settings"))
        self.actionLoad_settings.setText(_translate("MainWindow", "Load settings"))
        self.actionLoad_settings.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionSave_settings.setText(_translate("MainWindow", "Save settings"))
        self.actionSave_settings.setShortcut(_translate("MainWindow", "Ctrl+S"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

